server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tracker?useUnicode=true&amp&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
      username: root
      password: @jdbc.password@
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      additional-paths: src/main
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.joylife.tracker.dao.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  mappers: top.joylife.tracker.dao.MyMapper
  identity: MYSQL
